In the logistic regression example, I gave you a new iris data:

4.8,2.5,5.3,2.4

Please classify this flower using KNN (with all libs available as you like)

Here is a good scikit example you can use:

    Reference [1]
    Packed as a notebook [2]

In [1]:
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
iris_data = iris.data
iris_labels = iris.target
iris_data[0:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

***Trying out different ways to normalize data***

In [2]:
norm = np.linalg.norm(iris_data)
normed_iris_data1 = iris_data/norm
normed_iris_data1[0:10]

array([[0.05221703, 0.03583522, 0.01433409, 0.00204773],
       [0.0501693 , 0.0307159 , 0.01433409, 0.00204773],
       [0.04812157, 0.03276363, 0.01331022, 0.00204773],
       [0.04709771, 0.03173976, 0.01535795, 0.00204773],
       [0.05119316, 0.03685908, 0.01433409, 0.00204773],
       [0.05528862, 0.03993067, 0.01740568, 0.00409545],
       [0.04709771, 0.03481135, 0.01433409, 0.00307159],
       [0.05119316, 0.03481135, 0.01535795, 0.00204773],
       [0.04504998, 0.02969204, 0.01433409, 0.00204773],
       [0.0501693 , 0.03173976, 0.01535795, 0.00102386]])

In [3]:
from mlxtend.preprocessing import standardize
normed_iris_data3 = standardize(iris_data)
normed_iris_data3[0:10]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ],
       [-0.53717756,  1.93979142, -1.16971425, -1.05217993],
       [-1.50652052,  0.78880759, -1.34022653, -1.18381211],
       [-1.02184904,  0.78880759, -1.2833891 , -1.3154443 ],
       [-1.74885626, -0.36217625, -1.34022653, -1.3154443 ],
       [-1.14301691,  0.09821729, -1.2833891 , -1.44707648]])

In [4]:
test_data = np.array([4.8,2.5,5.3,2.4])
normed_test_data = standardize(test_data)
normed_test_data

array([[ 0.80003628],
       [-0.95242415],
       [ 1.18100594],
       [-1.02861808]])

In [5]:
distances = np.zeros([len(normed_iris_data3)])
distances

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
counter = 0
for row in normed_iris_data3:
    distances[counter] = np.linalg.norm(row - normed_test_data)
    counter += 1
    
distances 

array([6.12411537, 5.94996036, 6.23193041, 6.21505655, 6.36593425,
       6.48896432, 6.35277569, 6.01460693, 6.5471431 , 6.01905382,
       6.27842627, 6.14986285, 6.16630172, 6.89659943, 7.08684091,
       8.08386651, 6.66639956, 6.01571764, 6.23619084, 6.56732492,
       5.66017747, 6.24628365, 6.93333872, 5.41808534, 6.02195764,
       5.76070022, 5.75426954, 6.00782561, 5.918263  , 6.08666755,
       5.94731284, 5.53712825, 7.51256193, 7.64684847, 5.89698756,
       5.99875126, 5.96443302, 6.55964285, 6.55990799, 5.93664055,
       6.14353128, 7.22270348, 6.58742299, 5.73039688, 6.31070273,
       5.93740684, 6.62382462, 6.29414354, 6.32440292, 5.96081281,
       5.07090318, 4.42597065, 4.99073736, 5.38473213, 4.63450642,
       4.27854488, 4.5532597 , 5.56156526, 4.56874191, 4.630571  ,
       6.65090203, 4.11916611, 5.66346715, 4.28220708, 4.12006153,
       4.60000903, 4.21371415, 4.37539023, 5.80212969, 4.79855699,
       4.51153438, 4.23514021, 5.1108195 , 4.35168397, 4.33524

In [7]:
sorted_distance_indices = np.argsort(distances)
sorted_distance_indices

array([ 95,  88,  61,  96,  64,  91,  97,  99,  66,  71,  78,  55,  63,
        84,  82,  74,  73,  67,  94,  51, 138,  75,  70,  85,  92, 127,
        56,  58,  79, 149,  65,  59,  54, 133,  90, 126,  86,  83,  69,
        89, 121,  77, 123, 137, 101, 142,  76, 103,  52, 116, 134,  50,
       147, 110,  80,  72,  81,  98, 111,  53, 113, 146, 128,  23, 115,
       114,  87, 106, 132,  31, 104,  57, 112, 148, 145, 139,  20, 124,
        62,  43,  93,  26,  25, 141, 129,  68, 136, 119, 140,  34, 108,
        28,  39,  45,  30,   1,  49,  36,  35,  27, 143,   7,  17,   9,
       125, 120,  24, 100, 102,  29,   0,  40,  11,  12, 144,   3,   2,
        18,  21,  10,  47,  44, 107,  48,   6,   4,   5, 130,   8,  37,
        38,  19,  42,  46,  60,  16,  13,  22,  14, 105, 135, 109,  41,
       122,  32,  33, 118,  15, 131, 117])

In [9]:
k = int(np.sqrt(len(normed_iris_data3)))
k

12

In [16]:
k_nearest_iris_names = iris_labels[sorted_distance_indices[0:k]]
k_nearest_iris_names

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
iris['target_names'][1]

'versicolor'

In [18]:
if (np.all(k_nearest_iris_names == k_nearest_iris_names[0])):
    print('iris name is', iris['target_names'][k_nearest_iris_names[0]])
else:
    print('iris name is unclear.')

iris name is versicolor
